name: Rust PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  audit:
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deny
      uses: EmbarkStudios/cargo-deny-action@v1      
    - name: Check Format
      run: cargo fmt --all -- --check
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/shared-build.yml
    with:
      os: ${{ matrix.os }}